name: Metrics - Languages

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Isabelle-Matos
          base: header, repositories
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: ""
          plugin_languages_limit: 8
