name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ SECRETS.METRICS_TOKEN }} # (ou GITHUB_TOKEN)
          user: Isabelle-Matos
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_lines: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
