name: Generate Snake

on:
  # Executa automaticamente a cada 24 horas
  schedule:
    - cron: "0 0 * * *"
  
  # Permite rodar manualmente na aba Actions
  workflow_dispatch:
  
  # Executa sempre que houver um commit na branch main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/git-contribution-grid.svg

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
